require_relative '../../lib/lib'
require_relative '../../config'



docker_tasks 'mesos-common' do
  from 'centos:7'

  run 'rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm'
  run yum_install('mesos')
end
