require_relative '../../lib/lib'
require_relative '../../config'



docker_tasks \
    'mesos-master',
    '--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --net=host -e id=1' do
  from "#{DOCKER_USER}/mesos-common"

  run YUM_INSTALL, 'marathon chronos mesosphere-zookeeper'

  # mesos-master

  run "echo #{MASTERS.length} > /etc/mesos-master/quorum"

  # zookeeper

  zoo_cfg_content = MASTERS.map.with_index do |hostname, i|
    "server.#{i + 1}=#{hostname}:2888:3888"
  end.join "\n"

  servers = 'servers'
  File.write servers, zoo_cfg_content
  servers_dest = "/root/#{servers}"
  copy servers, servers_dest

  zookeeper_conf_dir = '/etc/zookeeper/conf'
  zoo_cfg = "#{zookeeper_conf_dir}/zoo.cfg"
  run "cp #{zookeeper_conf_dir}/zoo_sample.cfg #{zoo_cfg}"
  run "cat #{servers_dest} >> #{zoo_cfg}"

  # systemd

  run 'systemctl disable mesos-slave'

  ['mesos-master', 'zookeeper', 'marathon', 'chronos'].map do |service|
    run "systemctl enable #{service}"
  end

  cmd 'echo $id > /var/lib/zookeeper/myid && exec /usr/sbin/init'
end
