require_relative '../../lib/lib'
require_relative '../../config'



docker_tasks 'mesos-master' do
  from "#{DOCKER_USER}/mesos-common"

  env :container, :docker

  run '(cd /lib/systemd/system/sysinit.target.wants && for f in *; do [ $f == systemd-tmpfiles-setup.service ] || rm -f $f; done) && \
       rm -f /lib/systemd/system/multi-user.target.wants/* && \
       rm -f /etc/systemd/system/*.wants/* && \
       rm -f /lib/systemd/system/local-fs.target.wants/* && \
       rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
       rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
       rm -f /lib/systemd/system/basic.target.wants/* && \
       rm -f /lib/systemd/system/anaconda.target.wants/*'

  run yum_install('marathon', 'chronos', 'mesosphere-zookeeper')

  # mesos-master

  run "echo zk://#{MASTERS.map{ |h| "#{h}:2181" }.join ','}/mesos | tee /etc/mesos/zk"
  run "echo #{MASTERS.length} > /etc/mesos-master/quorum"

  # zookeeper

  zoo_cfg_content = MASTERS.map.with_index do |hostname, i|
    "server.#{i + 1}=#{hostname}:2888:3888"
  end.join "\n"

  servers = 'servers'
  File.write servers, zoo_cfg_content
  servers_dest = "/root/#{servers}"
  copy servers, servers_dest

  zookeeper_conf_dir = '/etc/zookeeper/conf'
  zoo_cfg = "#{zookeeper_conf_dir}/zoo.cfg"
  run "cp #{zookeeper_conf_dir}/zoo_sample.cfg #{zoo_cfg}"
  run "cat #{servers_dest} >> #{zoo_cfg}"

  # systemd

  run 'systemctl disable mesos-slave'
  run 'systemctl enable mesos-master zookeeper marathon chronos'

  cmd 'echo $id > /var/lib/zookeeper/myid && exec /usr/sbin/init'
end
