require_relative '../../lib/lib'
require_relative '../../config'



docker_tasks 'mesos-agent' do
  from "#{DOCKER_USER}/mesos-common"

  env :MESOS_MASTER, "zk://#{MASTERS.map{ |h| h + ':2181' }.join ','}/mesos"

  cmd 'mesos-agent --no-systemd_enable_support'
end
