require_relative '../lib/lib'
require_relative '../config'



docker_tasks 'mesos-master', '--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro' do
  from 'raviqqe/mesos-common'

  # mesos-master

  run "echo #{MASTERS.length} > /etc/mesos-master/quorum"

  # zookeeper

  run "echo #{MASTERS.index(`hostname`.strip) + 1} > /var/lib/zookeeper/myid"

  zoo_cfg_content = MASTERS.map.with_index do |hostname, i|
    "server.#{i + 1}=#{hostname}:2888:3888"
  end.join "\n"

  zoo_cfg = 'zoo.cfg'
  File.write zoo_cfg, zoo_cfg_content
  copy zoo_cfg, "/etc/zookeeper/conf/#{zoo_cfg}"

  # systemd

  run 'systemctl disable mesos-slave'

  ['mesos-master', 'zookeeper', 'marathon', 'chronos'].map do |service|
    run "systemctl enable #{service}"
  end

  expose 2181, 4400, 5050, 8080, '2888-3888'
end
