require_relative '../lib/lib'



docker_tasks 'mesos-master' do
  from 'centos:7'

  run 'rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm'
  run 'yum -y install mesos marathon chronos docker'
end
