require_relative '../lib/lib'
require_relative '../config'



docker_tasks 'mesos-master', '--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro' do
  from 'centos:7'

  env :container, :docker

  run 'rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm'
  run 'yum -y install mesos marathon chronos docker mesosphere-zookeeper'

  # mesos-master

  run "echo #{MASTERS.length} > /etc/mesos-master/quorum"

  # zookeeper

  run "echo #{MASTERS.index(`hostname`.strip) + 1} > /var/lib/zookeeper/myid"

  zoo_cfg_content = MASTERS.map.with_index do |hostname, i|
    "server.#{i + 1}=#{hostname}:2888:3888"
  end.join "\n"

  zoo_cfg = 'zoo.cfg'
  File.write zoo_cfg, zoo_cfg_content
  copy zoo_cfg, "/etc/zookeeper/conf/#{zoo_cfg}"

  run "echo zk://#{MASTERS.map{ |h| "#{h}:2181" }.join ','}/mesos > /etc/mesos/zk"

  # systemd

  run '(cd /lib/systemd/system/sysinit.target.wants && for f in *; do [ $f == systemd-tmpfiles-setup.service ] || rm -f $f; done) && \
       rm -f /lib/systemd/system/multi-user.target.wants/* && \
       rm -f /etc/systemd/system/*.wants/* && \
       rm -f /lib/systemd/system/local-fs.target.wants/* && \
       rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
       rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
       rm -f /lib/systemd/system/basic.target.wants/* && \
       rm -f /lib/systemd/system/anaconda.target.wants/*'

  run 'systemctl disable mesos-slave'

  ['mesos-master', 'zookeeper', 'marathon', 'chronos'].map do |service|
    run "systemctl enable #{service}"
  end

  expose 2181, 4400, 5050, 8080, '2888-3888'

  cmd '/usr/sbin/init'
end
